<tr>
    <td>%PLAN_NAME%</td>
    <td>%PRICE%</td>
    <td>%NO_OF_REMAINING_DAYS%</td>
    <td>%PURCHASED_ON%</td>
    <td>%INMAILS_RECEIVED%</td>
    <td>%INMAILS_UTILIZED%</td>
    <td>%INMAILS_OUTSTANDING%</td>
</tr>
